import {test,expect} from 'vitest';
import * as native from '../src/lib/lot-operational-evidence';
import {createFieldBoundProtocol} from '../src/lib/field-bound-protocol.mjs';
function fixture(){
 const context:any={target:{kind:'lot',publicationId:'invented-role',lotId:'invented-lot'},dependency:{hash:'invented'},projectBarrier:{reason:'not_reviewed'},targetContent:{identity:{detailUrl:'https://example.invalid/role'},selectedLot:{path:'/lots/1',record:{id:'invented-lot',partialOffersNote:{it:'Sono ammesse offerte che riguardano singoli lotti.'}}},projectSections:{base:{participantLotsLimitationNote:{it:'L’offerente ha il diritto di presentare un’offerta per più lotti.'}},dates:{offerDeadline:'2030-02-01T23:59:00+01:00'},'project-info':{offerSpecificNote:{it:'L’offerta completa deve essere presentata entro il 1 febbraio 2030.'}},correction:{remarks:{it:'Nuovo termine per la presentazione dell’offerta: 01.02.2030'}}}}};
 const request=native.buildOperationalEvidenceRequest(context),p=createFieldBoundProtocol(native,request),id=(path:string)=>{const row=p.catalog.find((x:any)=>x.path===path);if(!row)throw Error('Invented field absent');return row.fieldId;};
 const answer={binding:p.binding,country:null,countryEvidence:[],canton:null,cantonEvidence:[],city:null,cityEvidence:[],deadline:{value:'2030-02-01T23:59:00+01:00',appliesToTarget:true,dateFieldId:id('/dates/offerDeadline'),submissionFieldIds:[id('/project-info/offerSpecificNote/it')],lotApplicabilityFieldIds:[id('/base/participantLotsLimitationNote/it')],otherEvidenceFieldIds:[] as string[]},rationale:'Invented fixture only',issues:[]};return {context,p,id,answer};
}
test('instructions state exact native role paths and no automatic sufficiency',()=>{const f=fixture(),s=f.p.readingTask().system;for(const text of ['dateFieldId richiede /offerDeadline','submissionFieldIds richiede project_context','/{base,project-info}/participantLotsLimitationNote/','partialOffersNote','correction/remarks','non attestazioni automatiche','value null e motivazione'])expect(s).toContain(text);});
test('selected lot partial-offer note remains invalid as applicability',()=>{const f=fixture();f.answer.deadline.lotApplicabilityFieldIds=[f.id('/lots/1/partialOffersNote/it')];expect(()=>f.p.decodeReading(f.answer)).toThrow('Lot applicability role references wrong original field');});
test('correction remark remains invalid as submission role',()=>{const f=fixture();f.answer.deadline.submissionFieldIds=[f.id('/correction/remarks/it')];expect(()=>f.p.decodeReading(f.answer)).toThrow('Submission role references wrong original field');});
test('valid base role plus supplemental lot and correction evidence preserves originals',()=>{const f=fixture();f.answer.deadline.otherEvidenceFieldIds=[f.id('/lots/1/partialOffersNote/it'),f.id('/correction/remarks/it')];const a=f.p.decodeReading(f.answer);expect(a.deadline).toBe(f.answer.deadline.value);expect(a.deadlineEvidence.map(x=>x.path)).toContain('/lots/1/partialOffersNote/it');expect(a.deadlineEvidence.map(x=>x.path)).toContain('/correction/remarks/it');});
test('supplementary evidence cannot replace missing applicability role',()=>{const f=fixture();f.answer.deadline.lotApplicabilityFieldIds=[];f.answer.deadline.otherEvidenceFieldIds=[f.id('/base/participantLotsLimitationNote/it')];expect(()=>f.p.decodeReading(f.answer)).toThrow('Shared date requires explicit submission and lot-applicability selections');});
test('correct path does not bypass conflicting original applicability text',()=>{const f=fixture();f.context.targetContent.projectSections.base.participantLotsLimitationNote.it='Solo il lotto 1.';const request=native.buildOperationalEvidenceRequest(f.context),p=createFieldBoundProtocol(native,request);f.answer.binding=p.binding;expect(()=>p.decodeReading(f.answer)).toThrow('Shared deadline lacks explicit lot applicability scope');});
