import {test,expect} from 'vitest';
import * as native from '../src/lib/lot-operational-evidence';
import {createFieldBoundProtocol} from '../src/lib/field-bound-protocol.mjs';
function fixture(){
 const context:any={target:{kind:'lot',publicationId:'invented-coverage',lotId:'invented-lot'},dependency:{hash:'invented'},projectBarrier:{reason:'not_reviewed'},targetContent:{identity:{detailUrl:'https://example.invalid/coverage'},selectedLot:{path:'/lots/1',record:{id:'invented-lot',orderAddress:{countryId:'CH'},title:{it:'Sede inventata in Ticino'},executionDescription:{it:'Sede inventata in Ticino'}}},projectSections:{base:{country:'CH',participantLotsLimitationNote:{it:'L’offerente ha il diritto di presentare un’offerta per più lotti.'}},dates:{offerDeadline:'2030-02-01T23:59:00+01:00'},'project-info':{participantLotsLimitationNote:{it:'L’offerente ha il diritto di presentare un’offerta per più lotti.'},offerSpecificNote:{it:'L’offerta completa deve essere presentata entro il 1 febbraio 2030.'}}}}};
 const request=native.buildOperationalEvidenceRequest(context),p=createFieldBoundProtocol(native,request),id=(path:string)=>{const row=p.catalog.find((x:any)=>x.path===path);if(!row)throw Error('Invented field absent');return row.fieldId;};
 const reading={binding:p.binding,country:'CH',countryEvidence:[id('/lots/1/orderAddress/countryId')],canton:'TI',cantonEvidence:[id('/lots/1/title/it'),id('/lots/1/executionDescription/it')],city:null,cityEvidence:[],deadline:{value:'2030-02-01T23:59:00+01:00',appliesToTarget:true,dateFieldId:id('/dates/offerDeadline'),submissionFieldIds:[id('/project-info/offerSpecificNote/it')],lotApplicabilityFieldIds:[id('/base/participantLotsLimitationNote/it'),id('/project-info/participantLotsLimitationNote/it')],otherEvidenceFieldIds:[]},rationale:'Invented coverage fixture only',issues:[]};
 const coverage=JSON.parse(p.reviewTask(reading).prompt).reviewProofCoverage;
 const review:any={binding:p.binding,checks:Object.fromEntries(['country','canton','city','deadline'].map(k=>[k,{verdict:k==='city'?'not_verifiable':'supported',evidence:[...coverage[k].ownProofIds],rationale:'Independent invented review assertion, not a real semantic approval'}])),issues:[]};
 const metadata={id:'invented-review',at:'2026-10-10T00:00:00Z',model:'invented-offline-model'};return {context,request,p,id,reading,coverage,review,metadata};
}
test('review explicitly lists exact own IDs for every field with null coverage retained',()=>{const f=fixture();expect(f.coverage.country.ownProofIds).toEqual(f.reading.countryEvidence);expect(f.coverage.canton.ownProofIds).toEqual(f.reading.cantonEvidence);expect(f.coverage.city).toEqual({ownProofIds:[],completeCoverageRequired:false});expect(f.coverage.deadline.ownProofIds).toEqual([f.reading.deadline.dateFieldId,...f.reading.deadline.submissionFieldIds,...f.reading.deadline.lotApplicabilityFieldIds]);expect(f.coverage.country.completeCoverageRequired).toBe(true);});
test('equal text at distinct scopes and paths never collapses proof identities',()=>{const f=fixture();const payload=JSON.parse(f.p.reviewTask(f.reading).prompt);const rows=payload.originalProofCatalog.filter((r:any)=>f.reading.deadline.lotApplicabilityFieldIds.includes(r[0]));expect(rows).toHaveLength(2);expect(rows[0][3]).toEqual(rows[1][3]);expect(rows[0][2]).not.toBe(rows[1][2]);expect(f.coverage.deadline.ownProofIds).toContain(rows[0][0]);expect(f.coverage.deadline.ownProofIds).toContain(rows[1][0]);expect(native.decodeOperationalTaskPrompt(f.p.reviewTask(f.reading).prompt).source).toEqual(f.request.data);});
test('schema-valid omission remains native rejection; decoder never fills evidence',()=>{const f=fixture();f.review.checks.canton.evidence.pop();expect(f.p.reviewSchema.safeParse(f.review).success).toBe(true);const decoded=f.p.decodeReview(f.review);expect(decoded.checks.canton.evidence).toHaveLength(1);expect(()=>f.p.record(f.reading,f.review,f.metadata)).toThrow('Operational review did not verify each own proof');});
test('duplicate text cannot substitute for another own deadline path',()=>{const f=fixture();f.review.checks.deadline.evidence=f.review.checks.deadline.evidence.filter((x:string)=>x!==f.id('/project-info/participantLotsLimitationNote/it'));expect(()=>f.p.record(f.reading,f.review,f.metadata)).toThrow('Operational review did not verify each own proof');});
test('same quote from project scope cannot replace selected-lot country proof',()=>{const f=fixture();f.review.checks.country.evidence=[f.id('/base/country')];expect(()=>f.p.record(f.reading,f.review,f.metadata)).toThrow('Operational review did not verify each own proof');f.reading.countryEvidence=[f.id('/base/country')];expect(()=>f.p.reviewTask(f.reading)).toThrow('Operational location lacks selected-lot proof');});
test('a false fact independently contradicted is rejected despite complete coverage',()=>{const f=fixture();f.reading.canton='ZH';f.review.checks.canton.verdict='contradicted';f.review.checks.canton.rationale='Invented source says Ticino, not Zurich';expect(()=>f.p.record(f.reading,f.review,f.metadata)).toThrow('Operational review contradicts reading');});
test('independent uncertainty remains representable and blocks a non-null fact',()=>{const f=fixture();f.review.checks.canton.verdict='not_verifiable';expect(f.p.reviewSchema.safeParse(f.review).success).toBe(true);expect(()=>f.p.record(f.reading,f.review,f.metadata)).toThrow('Operational review did not verify fact');});
test('null and not_verifiable require no invented support; explicit complete fixture is structurally recordable',()=>{const f=fixture();expect(f.p.record(f.reading,f.review,f.metadata).answer.city).toBeNull();expect(f.review.checks.city.verdict).toBe('not_verifiable');expect(f.review.checks.city.evidence).toEqual([]);const system=f.p.reviewTask(f.reading).system;expect(system).toContain('non è una verifica');expect(system).toContain('decoder non completa');expect(system).toContain('not_verifiable');});
