import assert from 'node:assert/strict';import {test} from 'vitest';import Ajv2020 from 'ajv/dist/2020.js';import {buildSourceInterpretationRequest,priceAwardContractFamilyIds,type SourceInterpretationContext} from '../src/lib/source-interpretation';
function ctx(flag:unknown=true,scope='project_context'):SourceInterpretationContext {const prefix=scope==='selected_lot'?'/lots/3/criteria/awardCriteria/0':'/criteria/awardCriteria/0';const passage=(id:string,lang:string,text:string)=>({id,scope,role:'context',rawPath:prefix+'/description/'+lang,text,startUtf16:0,endUtf16:text.length,url:'https://example.invalid/original'});return {binding:{target:{kind:'project',publicationId:'invented-price'},source:{observationId:'invented-observation',snapshotHash:'a'.repeat(64)},fieldsHash:'b'.repeat(64),shapeEpochToken:'invented-shape',model:'gpt-6-luna',reasoningEffort:'medium',maxTokens:8192},targetScope:scope,coverage:{completeProvidedSource:true,linkedDocumentsRead:false,sourceUtf16:60,fields:3,chunks:1},body:{target:{kind:'project',lot:null},classifications:[],fields:[{scope,rawPath:prefix+'/isPriceCriterion',value:flag}],passages:[passage('s1','it','Originale opaco A'),passage('s2','fr','Original opaque B'),{...passage('s3','it','Prestazione inventata originale.'),role:'service',rawPath:scope==='selected_lot'?'/lots/3/orderDescription/it':'/procurement/orderDescription/it'}]},readings:[]} as SourceInterpretationContext;}
const deref=(schema:any,node:any):any=>node?.$ref?deref(schema,node.$ref.slice(2).split('/').reduce((x:any,k:string)=>x[k],schema)):node;
const selector=(request:any,family:string,branch=0)=>{const schema=request.responseFormat.json_schema.schema,base=deref(schema,schema.oneOf[branch]),families=deref(schema,base.properties.contractClauseDetails);return new Ajv2020({strict:false}).compile({$defs:schema.$defs,definitions:{owned:families.properties[family]},$ref:'#/definitions/owned'})};
test('Typed true restricts small producer family in every status without approving meaning',()=>{const c=ctx(),before=JSON.stringify(c),r=buildSourceInterpretationRequest(c),f=r.contractDetailFamilies[0];assert(f);for(let branch=0;branch<3;branch++){const v=selector(r,f.id,branch),row={kind:'execution_condition',scope:'project_context',sourceRefs:['s1','s2'],originalText:true};assert(v([row]));assert.equal(v([{...row,kind:'technical_specification'}]),false)}assert.equal(JSON.stringify(c),before);assert.deepEqual(f.sourceRefs,['s1','s2']);});
test('False null and string true do not trigger price restriction',()=>{for(const value of [false,null,'true']){const r=buildSourceInterpretationRequest(ctx(value)),v=selector(r,r.contractDetailFamilies[0].id);assert(v([{kind:'technical_specification',scope:'project_context',sourceRefs:['s1','s2'],originalText:true}]))}});
test('Same original criterion and scope required, neighboring flag cannot supply ownership',()=>{const f=[{id:'s1',scope:'project_context',rawPath:'/criteria/awardCriteria/0/description'}];for(const field of [{rawPath:'/criteria/awardCriteria/1/isPriceCriterion',scope:'project_context',value:true},{rawPath:'/criteria/awardCriteria/0/isPriceCriterion',scope:'selected_lot',value:true},{rawPath:'/metadata/criteria/awardCriteria/0/isPriceCriterion',scope:'project_context',value:true}])assert.deepEqual(priceAwardContractFamilyIds(f,[field]),[])});
test('Duplicate conflicting flags stay unbound without choosing authority',()=>{const f=[{id:'s1',scope:'project_context',rawPath:'/criteria/awardCriteria/0/description'}],rawPath='/criteria/awardCriteria/0/isPriceCriterion';assert.deepEqual(priceAwardContractFamilyIds(f,[{rawPath,scope:'project_context',value:true},{rawPath,scope:'project_context',value:false}]),[])});
test('Selected-lot own criterion binds without rewriting original scope',()=>{const c:any=ctx(true,'selected_lot');c.binding.target={kind:'lot',publicationId:'invented-price',sourceProjectId:'invented-project',lotId:'invented-lot'};c.body.target={kind:'lot',lot:{id:'invented-lot',path:'/lots/3',headerPath:'/base/lots/3'}};const r=buildSourceInterpretationRequest(c),f=r.contractDetailFamilies[0],v=selector(r,f.id);assert.equal(f.scope,'selected_lot');assert(v([{kind:'execution_condition',scope:'selected_lot',sourceRefs:['s1','s2'],originalText:true}]));assert.equal(v([{kind:'technical_specification',scope:'selected_lot',sourceRefs:['s1','s2'],originalText:true}]),false)});
test('No inference from title weighting or qualification criterion',()=>{const f=[{id:'s1',scope:'project_context',rawPath:'/criteria/awardCriteria/0/description'},{id:'s2',scope:'project_context',rawPath:'/criteria/qualificationCriteria/0/description'}];assert.deepEqual(priceAwardContractFamilyIds(f,[{rawPath:'/criteria/awardCriteria/0/weighting',scope:'project_context',value:100}]),[]);assert.deepEqual(priceAwardContractFamilyIds(f,[{rawPath:'/criteria/awardCriteria/0/isPriceCriterion',scope:'project_context',value:true}]),['s1'])});
