import {test,expect} from "vitest";
import {buildSourceInterpretationRequest,recordSourceInterpretation} from "../src/lib/source-interpretation";
function fixture(selected="s1",grouped=false){
  const texts=["Raccolta e trasporto dei rifiuti. ","Documentazione dell'attività richiesta."];
  const passages=texts.map((text,i)=>({id:`s${i+1}`,text,scope:"project_context",role:"service",rawPath:grouped||i===0?"/procurement/orderDescription/it":"/optional/description/it",startUtf16:i&&grouped?texts[0].length:0,endUtf16:(i&&grouped?texts[0].length:0)+text.length,url:"https://example.invalid/owned"}));
  passages.push({id:"s3",text:"Fornitura di contenitori inventati.",scope:"project_context",role:"service",rawPath:"/base/title/it",startUtf16:0,endUtf16:34,url:"https://example.invalid/owned"});passages[2].endUtf16=passages[2].text.length;
  const context:any={binding:{target:{kind:"project",publicationId:"invented-duplicate"},source:{invented:true},fieldsHash:"a".repeat(64),shapeEpochToken:"invented",model:"gpt-6-luna",reasoningEffort:"medium",maxTokens:8192},targetScope:"project_context",coverage:{completeProvidedSource:true,linkedDocumentsRead:false,sourceUtf16:passages.reduce((n,p)=>n+p.text.length,0),fields:0,chunks:1},body:{target:{kind:"project",lot:null},passages,fields:[],classifications:[]},readings:[]};
  const request=buildSourceInterpretationRequest(context),prompt=JSON.parse(request.prompt),group=Object.keys(prompt.originalLiteralCatalogue).find(k=>k.startsWith("g")),literal=(prompt.originalLiteralCatalogue[selected]??prompt.originalLiteralCatalogue[group!])[0][0];
  const value:any={evidenceFormat:"source_selections_v21_owned",status:"resolved",targetRef:selected,summary:"Invented structural fixture",summaryAdditionalSourceRefs:[],details:[],issues:[],classificationReadingsById:{},contractClauseDetails:Object.fromEntries(request.contractDetailFamilies.map(f=>[f.id,[{kind:"technical_specification",scope:f.scope,sourceRefs:f.sourceRefs,originalText:true}]])),components:[{description:passages.find(p=>p.id===selected)!.text,importance:"not_stated",role:selected==="s3"?"supply":"execute",roleEvidence:{state:"identified",scope:"project_context",actionSelection:{literalSelectionId:literal}},meaning:{state:"identified",statement:passages.find(p=>p.id===selected)!.text,objectSelection:{literalSelectionId:literal},basis:"explicit_text"},evidenceDeclaration:{basis:"selected_action_object_plus_explicit_additional_originals",additionalEvidence:[]}}]};
  const record=()=>recordSourceInterpretation(value,request,{id:"invented-only",at:"2030-01-01T00:00:00Z",model:"gpt-6-luna"});return {request,prompt,value,group,record};
}
test("same action/object owner is declared once without additional duplicate",()=>{const f=fixture(),r=f.record();expect(r.response.components[0].sourceRefs).toEqual(["s1"]);expect(r.response.components[0].roleEvidence.sourceRefs).toEqual(["s1"]);});
test("same owner additional remains rejected even when offered for another phrase",()=>{const f=fixture();f.value.components[0].evidenceDeclaration.additionalEvidence=[{sourceRef:"s1"}];expect(f.record).toThrow("Repeated additional owned original evidence");});
test("additional group overlapping a selected owner remains rejected",()=>{const f=fixture("s1",true);expect(f.group).toBeDefined();f.value.components[0].evidenceDeclaration.additionalEvidence=[{sourceRef:f.group}];expect(f.record).toThrow("Repeated additional owned original evidence");});
test("group and one of its members cannot both be additional evidence",()=>{const f=fixture("s3",true);f.value.components[0].evidenceDeclaration.additionalEvidence=[{sourceRef:f.group},{sourceRef:"s2"}];expect(f.record).toThrow("Repeated additional owned original evidence");});
test("a disjoint whole group still expands to its exact original members",()=>{const f=fixture("s3",true);f.value.components[0].evidenceDeclaration.additionalEvidence=[{sourceRef:f.group}];expect(f.record().response.components[0].sourceRefs).toEqual(["s3","s1","s2"]);});
test("guidance explains ownership without promoting a fragment to proof of other facts",()=>{const f=fixture(),rule=f.prompt.originalLiteralRule;expect(rule).toContain("I proprietari sN di action/object sono già nell'evidence");expect(rule).toContain("Un gN aggiuntivo espande tutti i suoi sN");expect(rule).toContain("frammento non approvano altri fatti");});
