import assert from 'node:assert/strict';
import {test} from 'vitest';
import Ajv2020 from 'ajv/dist/2020.js';
import {buildSourceInterpretationRequest,administrativeAwardContractFamilyIds,sourceAwardFieldRoleContext} from '../src/lib/source-interpretation';
function context(scope='project_context',description='Material must resist temperature of 80 degrees.'):any {
 const prefix=scope==='selected_lot'?'/lots/3/criteria':'/criteria';
 const passage=(id:string,rawPath:string,text:string)=>({id,scope,role:'context',rawPath,text,startUtf16:0,endUtf16:text.length,url:'https://example.invalid/original'});
 return {binding:{target:{kind:'project',publicationId:'invented-role'},source:{observationId:'invented-observation',snapshotHash:'a'.repeat(64)},fieldsHash:'b'.repeat(64),shapeEpochToken:'invented-shape',model:'gpt-6-luna',reasoningEffort:'medium',maxTokens:8192},targetScope:scope,coverage:{completeProvidedSource:true,linkedDocumentsRead:false,sourceUtf16:200,fields:3,chunks:1},body:{target:{kind:'project',lot:null},classifications:[],fields:[{scope,rawPath:prefix+'/awardCriteria/0/isPriceCriterion',value:false},{scope,rawPath:prefix+'/awardCriteria/0/verification',value:null},{scope,rawPath:prefix+'/awardCriteria/0/weighting',value:30}],passages:[passage('s1',prefix+'/awardCriteriaSelection','criteria_defined'),passage('s2',prefix+'/awardCriteria/0/description/it',description),{...passage('s3',scope==='selected_lot'?'/lots/3/orderDescription/it':'/procurement/orderDescription/it','Original purchased material.'),role:'service'}]},readings:[]};
}
const deref=(schema:any,n:any):any=>n?.$ref?deref(schema,n.$ref.slice(2).split('/').reduce((x:any,k:string)=>x[k],schema)):n;
const selector=(r:any,id:string,branch=0)=>{const schema=r.responseFormat.json_schema.schema,root=deref(schema,schema.oneOf[branch]),families=deref(schema,root.properties.contractClauseDetails);return new Ajv2020({strict:false}).compile({$defs:schema.$defs,definitions:{own:families.properties[id]},$ref:'#/definitions/own'})};
test('Administrative selection field rejects technical kind in noncompact producer for all statuses',()=>{const c=context(),before=JSON.stringify(c),r=buildSourceInterpretationRequest(c);for(let branch=0;branch<3;branch++){const v=selector(r,'s1',branch),row={kind:'execution_condition',scope:'project_context',sourceRefs:['s1'],originalText:true};assert(v([row]));assert.equal(v([{...row,kind:'technical_specification'}]),false)}assert.equal(JSON.stringify(c),before)});
test('Nonprice material requirement retains technical selector and literal text',()=>{const c=context(),r=buildSourceInterpretationRequest(c),v=selector(r,'s2');assert(v([{kind:'technical_specification',scope:'project_context',sourceRefs:['s2'],originalText:true}]));assert.equal(r.body.passages[1].text,c.body.passages[1].text)});
test('Reference and material criterion texts get same structural lookup, no keyword classification',()=>{const a=context('project_context','References of previous contracts.'),b=context('project_context','Original material must meet 80 degree temperature.');assert.deepEqual(sourceAwardFieldRoleContext(a.body),sourceAwardFieldRoleContext(b.body));assert(selector(buildSourceInterpretationRequest(a),'s2')([{kind:'technical_specification',scope:'project_context',sourceRefs:['s2'],originalText:true}]))});
test('Lookup groups only own criterion flag and verification, retains null and false fields',()=>{const c=context();c.body.fields.push({scope:'project_context',rawPath:'/criteria/awardCriteria/1/isPriceCriterion',value:true});const before=JSON.stringify(c.body),g=sourceAwardFieldRoleContext(c.body);assert.deepEqual(g.find(x=>x.rawPath==='/criteria/awardCriteria/0')!.fieldIndexes,[0,1,2]);assert.deepEqual(g.find(x=>x.rawPath==='/criteria/awardCriteria/1')!.fieldIndexes,[3]);assert.equal(JSON.stringify(c.body),before)});
test('Administrative-looking text in material description never supplies field ownership',()=>{const f=[{id:'s1',rawPath:'/criteria/awardCriteria/0/description',scope:'project_context'},{id:'s2',rawPath:'/metadata/awardCriteriaSelection',scope:'project_context'}];assert.deepEqual(administrativeAwardContractFamilyIds(f),[]);const c=context('project_context','criteria_defined');assert(selector(buildSourceInterpretationRequest(c),'s2')([{kind:'technical_specification',scope:'project_context',sourceRefs:['s2'],originalText:true}]))});
test('Lot ownership and same-name project fields remain separate without inheritance',()=>{const c=context('selected_lot');c.binding.target={kind:'lot',publicationId:'invented-role',sourceProjectId:'invented-project',lotId:'invented-lot'};c.body.target={kind:'lot',lot:{id:'invented-lot',path:'/lots/3',headerPath:'/base/lots/3'}};c.body.fields.push({scope:'project_context',rawPath:'/criteria/awardCriteria/0/isPriceCriterion',value:true});const r=buildSourceInterpretationRequest(c),g=sourceAwardFieldRoleContext(c.body);assert.deepEqual(g.find(x=>x.scope==='selected_lot'&&x.fieldRole==='award_criterion')!.fieldIndexes,[0,1,2]);assert(selector(r,'s2')([{kind:'technical_specification',scope:'selected_lot',sourceRefs:['s2'],originalText:true}]));assert.equal(selector(r,'s1')([{kind:'technical_specification',scope:'selected_lot',sourceRefs:['s1'],originalText:true}]),false)});
test('False null and absent price flags never imply nonprice criteria are nontechnical',()=>{for(const flag of [false,null,undefined]){const c=context();if(flag===undefined)c.body.fields.shift();else c.body.fields[0].value=flag;assert(selector(buildSourceInterpretationRequest(c),'s2')([{kind:'technical_specification',scope:'project_context',sourceRefs:['s2'],originalText:true}]))}});
test('Mixed prior references and current material requirements retain complete own text and both semantic choices',()=>{const text='Prior deliveries establish references. Current supplied unit must resist 80 degrees.',c=context('project_context',text);c.body.passages.push({...c.body.passages[1],id:'s4',rawPath:'/criteria/awardCriteria/0/title/it',text:'Original mixed criterion',endUtf16:24});const before=JSON.stringify(c.body),r=buildSourceInterpretationRequest(c),v=selector(r,'s2');for(const kind of ['technical_specification','execution_condition'])assert(v([{kind,scope:'project_context',sourceRefs:['s2'],originalText:true}]));assert.equal(JSON.stringify(c.body),before);assert.equal(r.body.passages[1].text,text);assert.deepEqual(sourceAwardFieldRoleContext(c.body).find(x=>x.fieldRole==='award_criterion')!.sourceRefs,['s2','s4'])});
