import assert from "node:assert/strict";import {test} from "vitest";import Ajv from "ajv/dist/2020.js";import {buildSourceInterpretationRequest,recordSourceInterpretation,readSourceInterpretation,validateSourceInterpretation,type SourceInterpretationContext} from "../src/lib/source-interpretation";
const body=(id:string,text:string,path:string,scope:"project_context"|"selected_lot"="project_context")=>({id,text,rawPath:path,scope,role:"service" as const,startUtf16:0,endUtf16:text.length,url:"https://example.invalid/invented-owned-source"});
function fixture(){const context:SourceInterpretationContext={binding:{target:{kind:"project",publicationId:"invented-owned"},source:{original:"invented"},fieldsHash:"a".repeat(64),shapeEpochToken:"invented",model:"invented-model",reasoningEffort:"medium",maxTokens:8192},targetScope:"project_context",coverage:{completeProvidedSource:true,linkedDocumentsRead:false,sourceUtf16:160,fields:3,chunks:1},readings:[],body:{target:{kind:"project",lot:null},classifications:[],fields:[],passages:[body("s1","Collecte et transport des déchets.","/procurement/orderDescription/fr"),body("s2","Raccolta e trasporto dei rifiuti.","/procurement/orderDescription/it"),{...body("s3","Destinazione: sito inventato.","/optional/location"),role:"context"}]}};const request=buildSourceInterpretationRequest(context);const catalogue=JSON.parse(request.prompt).originalLiteralCatalogue;const french=catalogue.s1[0][0];const value:any={evidenceFormat:"source_selections_v21_owned",status:"resolved",targetRef:"s2",summary:"Raccolta e trasporto dei rifiuti.",summaryAdditionalSourceRefs:[],details:[],issues:[],classificationReadingsById:{},contractClauseDetails:Object.fromEntries(request.contractDetailFamilies.map(f=>[f.id,[{kind:"technical_specification",scope:f.scope,sourceRefs:f.sourceRefs,originalText:true}]])),components:[{description:"Raccolta e trasporto dei rifiuti.",importance:"not_stated",role:"execute",evidenceDeclaration:{basis:"selected_action_object_plus_explicit_additional_originals",additionalEvidence:[]},roleEvidence:{state:"identified",scope:"project_context",actionSelection:{literalSelectionId:french}},meaning:{state:"identified",statement:"Servizio di raccolta e trasporto dei rifiuti.",objectSelection:{literalSelectionId:french},basis:"explicit_text"}}]};const meta={id:"invented-owned-record",at:"2030-01-01T00:00:00Z",model:"invented-model"};return {context,request,value,meta};}
test("New explicit basis projects selected French originals only, never summary Italian evidence",()=>{const {context,request,value,meta}=fixture();const before=JSON.stringify({context,value});const accepts=new Ajv({strict:false}).compile<any>(request.responseFormat.json_schema.schema);assert(accepts(value),JSON.stringify(accepts.errors));const rec=recordSourceInterpretation(value,request,meta);assert.deepEqual(rec.response.components[0].sourceRefs,["s1"]);assert.deepEqual(rec.response.components[0].roleEvidence.sourceRefs,["s1"]);assert.deepEqual(rec.response.components[0].meaning.objectRefs,["s1"]);assert.deepEqual(rec.response.summarySourceRefs,["s2"]);assert.equal(JSON.stringify({context,value}),before);});
test("Explicit additional originals remain owned and are not synthesized from prose",()=>{const {request,value,meta}=fixture();value.components[0].evidenceDeclaration.additionalEvidence=[{sourceRef:"s3"}];const rec=recordSourceInterpretation(value,request,meta);assert.deepEqual(rec.response.components[0].sourceRefs,["s1","s3"]);});
test("Missing explicit declaration or basis cannot become automatic evidence",()=>{for(const mutate of [(v:any)=>{delete v.components[0].evidenceDeclaration},(v:any)=>{delete v.components[0].evidenceDeclaration.basis},(v:any)=>{delete v.components[0].evidenceDeclaration.additionalEvidence}]){const {request,value,meta}=fixture();mutate(value);assert.throws(()=>recordSourceInterpretation(value,request,meta));}});
test("Unknown literal, foreign additional reference and source-overlap duplicates are rejected",()=>{for(const mutate of [(v:any)=>{v.components[0].roleEvidence.actionSelection.literalSelectionId="l999999"},(v:any)=>{v.components[0].evidenceDeclaration.additionalEvidence=[{sourceRef:"s999999"}]},(v:any)=>{v.components[0].evidenceDeclaration.additionalEvidence=[{sourceRef:"s1"}]},(v:any)=>{v.components[0].evidenceDeclaration.additionalEvidence=[{sourceRef:"s3"},{sourceRef:"s3"}]}]){const {request,value,meta}=fixture();mutate(value);assert.throws(()=>recordSourceInterpretation(value,request,meta));}});
test("Selected original action cannot cross the declared role scope",()=>{const {request,value,meta}=fixture();value.components[0].roleEvidence.scope="selected_lot";assert.throws(()=>recordSourceInterpretation(value,request,meta),/crosses declared scope/);});
test("New producer refuses the old evidence array rather than repairing it",()=>{const {request,value,meta}=fixture();value.components[0].evidence=[{sourceRef:"s2"}];assert.throws(()=>recordSourceInterpretation(value,request,meta));const original=fixture();original.value.evidenceFormat="source_selections_v20";delete original.value.components[0].evidenceDeclaration;original.value.components[0].evidence=[{sourceRef:"s2"}];const old=buildSourceInterpretationRequest(original.context,{legacyEvidenceSelectionProtocolForRegression:true});assert.throws(()=>recordSourceInterpretation(original.value,old,original.meta),/own component evidence and scope/);});

test("Nonservice catalogue entries cannot serve as action or object evidence",()=>{const {request,value,meta}=fixture();const contextId=JSON.parse(request.prompt).originalLiteralCatalogue.s3[0][0];value.components[0].meaning.objectSelection.literalSelectionId=contextId;assert.throws(()=>recordSourceInterpretation(value,request,meta));});
test("Selected plus additional originals keep the unchanged total reference bound",()=>{const {context,value,meta}=fixture();const extra=Array.from({length:32},(_,i)=>({...body("s"+(i+4),"Originale facoltativo "+i,"/optional/fact/"+i),role:"context" as const}));const extended={...context,body:{...context.body,passages:[...context.body.passages,...extra]}};const request=buildSourceInterpretationRequest(extended);value.components[0].evidenceDeclaration.additionalEvidence=extra.map(p=>({sourceRef:p.id}));assert.throws(()=>recordSourceInterpretation(value,request,meta),/original reference limit/);});

test("Identical text at another original path cannot substitute the selected owner",()=>{const {context,value,meta}=fixture();const duplicate={...context.body.passages[0],id:"s4",rawPath:"/project-info/title/fr"};const next={...context,body:{...context.body,passages:[...context.body.passages,duplicate]}};const request=buildSourceInterpretationRequest(next);value.contractClauseDetails=Object.fromEntries(request.contractDetailFamilies.map(f=>[f.id,[{kind:"technical_specification",scope:f.scope,sourceRefs:f.sourceRefs,originalText:true}]]));const selected=JSON.parse(request.prompt).originalLiteralCatalogue.s4[0][0];value.components[0].roleEvidence.actionSelection.literalSelectionId=selected;value.components[0].meaning.objectSelection.literalSelectionId=selected;const before=JSON.stringify(value);const record=recordSourceInterpretation(value,request,meta);assert.deepEqual(record.response.components[0].sourceRefs,["s4"]);assert.equal(JSON.stringify(value),before);const legacy=buildSourceInterpretationRequest(next,{legacyEvidenceSelectionProtocolForRegression:true});const old={...value,evidenceFormat:"source_selections_v20",components:value.components.map((c:any)=>{const {evidenceDeclaration:_,...rest}=c;return {...rest,evidence:[{sourceRef:"s1"}]}})};assert.throws(()=>recordSourceInterpretation(old,legacy,meta),/own component evidence and scope/);});


test("Owned recorder rejects markerless canonical input while saved records remain verifiable",()=>{const {request,value,meta}=fixture();const before=JSON.stringify(value);const saved=recordSourceInterpretation(value,request,meta);assert.equal(JSON.stringify(value),before);assert.throws(()=>recordSourceInterpretation(saved.response,request,meta),/requires its explicit request protocol/);assert(readSourceInterpretation(saved,request));assert(validateSourceInterpretation(saved.response,request));});
test("Owned recorder refuses foreign legacy, missing declarations and a forged canonical marker",()=>{for(const mutation of [(v:any)=>{v.evidenceFormat="source_selections_v20"},(v:any)=>{delete v.evidenceFormat},(v:any)=>{delete v.components[0].evidenceDeclaration}]){const {request,value,meta}=fixture();mutation(value);assert.throws(()=>recordSourceInterpretation(value,request,meta));}const {request,value,meta}=fixture();const saved=recordSourceInterpretation(value,request,meta);assert.throws(()=>recordSourceInterpretation({...saved.response,evidenceFormat:"source_selections_v21_owned"},request,meta));});
