import {createHash} from 'node:crypto';import {stableDocumentaryJson} from '../src/lib/documentary-observation';
import{test,expect}from'vitest';import{buildSourceEvidenceReadingRequest,recordSourceEvidenceReading,readSourceEvidenceReading}from'../src/lib/source-evidence-reading';
function fixture(sameText=false){const text=(id:string,t:string,path:string)=>({id,text:t,rawPath:path,scope:'project_context',role:id==='s3'?'context':'service',startUtf16:0,endUtf16:t.length,url:'https://example.invalid/SYNTHETIC_ONLY'});const context:any={binding:{target:{kind:'project',publicationId:'INVENTED_READER_DUPLICATE'},source:{original:'INVENTED'},fieldsHash:'a'.repeat(64),shapeEpochToken:'INVENTED',model:'invented-source-model',reasoningEffort:'medium',maxTokens:8192},targetScope:'project_context',coverage:{completeProvidedSource:true,linkedDocumentsRead:false,sourceUtf16:100,fields:0,chunks:1},readings:[],body:{target:{kind:'project',lot:null},fields:[],classifications:[],passages:[text('s1','Service collecte des dechets.','/procurement/orderDescription/fr'),text('s2',sameText?'Service collecte des dechets.':'Service maintenance des machines.','/procurement/secondService/it'),text('s3','Condition originale de disponibilite.','/optional/condition')]}},plan=buildSourceEvidenceReadingRequest(context,{model:'invented-reader',reasoningEffort:'high'});expect(plan.requests).toHaveLength(1);const one={kind:'performance',serviceRef:'s1',evidence:[{sourceRef:'s1'},{sourceRef:'s3'}]},value:any={chunkId:plan.requests[0].id,coverage:'complete',observations:[one],issues:[],missingDetails:[],classifications:[],requiredClauseSelections:Object.fromEntries(plan.requests[0].requiredClauseIds.map(id=>[id,[{collection:'observations'}]]))};return{plan,value,one,meta:{id:'INVENTED_LOCAL_NO_PASS',at:'2030-01-01T00:00:00Z',model:'invented-reader'}}}
const error='Repeated independent source observation selection';
test('single observation preserved',()=>{const f=fixture(),before=JSON.stringify(f.value),record=recordSourceEvidenceReading([f.value],f.plan,f.meta),r=readSourceEvidenceReading(record,f.plan);expect(r?.observations).toHaveLength(1);expect(JSON.stringify(f.value)).toBe(before)});
for(const mode of ['exact','reordered-evidence','implicit-anchor'])test('duplicate rejects '+mode+' without row deletion or inputmutation',()=>{const f=fixture(),second=structuredClone(f.one);if(mode==='reordered-evidence')second.evidence.reverse();if(mode==='implicit-anchor')second.evidence=second.evidence.filter(q=>q.sourceRef!=='s1');f.value.observations.push(second);const before=JSON.stringify(f.value);expect(()=>recordSourceEvidenceReading([f.value],f.plan,f.meta)).toThrow(error);expect(JSON.stringify(f.value)).toBe(before)});
test('same anchor different kind retains condition separately',()=>{const f=fixture();f.value.observations.push({...structuredClone(f.one),kind:'condition'});expect(readSourceEvidenceReading(recordSourceEvidenceReading([f.value],f.plan,f.meta),f.plan)?.observations).toHaveLength(2)});
test('different original service retains independent performance',()=>{const f=fixture();f.value.observations.push({kind:'performance',serviceRef:'s2',evidence:[{sourceRef:'s2'},{sourceRef:'s3'}]});expect(readSourceEvidenceReading(recordSourceEvidenceReading([f.value],f.plan,f.meta),f.plan)?.observations).toHaveLength(2)});
test('same anchor distinct original condition evidence remains distinct',()=>{const f=fixture();f.value.observations=[{kind:'condition',serviceRef:'s1',evidence:[]},{kind:'condition',serviceRef:'s1',evidence:[{sourceRef:'s3'}]}];expect(readSourceEvidenceReading(recordSourceEvidenceReading([f.value],f.plan,f.meta),f.plan)?.observations).toHaveLength(2)});
test('identical condition duplicated also rejects explicitly',()=>{const f=fixture();f.value.observations=[{...f.one,kind:'condition'},{...structuredClone(f.one),kind:'condition'}];expect(()=>recordSourceEvidenceReading([f.value],f.plan,f.meta)).toThrow(error)});
test('unknown evidence, repeated evidence ref and metadata integrity keep original rejection',()=>{for(const mode of ['foreign','repeat']){const f=fixture();f.value.observations[0].evidence.push({sourceRef:mode==='foreign'?'s999999':'s3'});expect(()=>recordSourceEvidenceReading([f.value],f.plan,f.meta)).toThrow(mode==='foreign'?'Source evidence reference outside its request':'Repeated source evidence references')}const f=fixture();expect(()=>recordSourceEvidenceReading([f.value],{...f.plan} as any,f.meta)).toThrow('Unverified source evidence plan')});

test('distinct original anchors with identical text remain distinct',()=>{const f=fixture(true);f.value.observations.push({kind:'performance',serviceRef:'s2',evidence:[{sourceRef:'s2'},{sourceRef:'s3'}]});expect(readSourceEvidenceReading(recordSourceEvidenceReading([f.value],f.plan,f.meta),f.plan)?.observations).toHaveLength(2)});

function duplicateFixture(){const f=fixture();f.value.observations.push(structuredClone(f.one));return f;}
for(const field of ['model','id','at'] as const)test('joint duplicate and invalid metadata '+field+' preserves integrity priority',()=>{const f=duplicateFixture();const metadata={...f.meta,[field]:field==='model'?'WRONG_MODEL':field==='id'?'':'INVALID_DATE'};expect(()=>recordSourceEvidenceReading([f.value],f.plan,metadata)).toThrow(field==='model'?'Source evidence model changed':'Invalid source evidence metadata')});
test('joint duplicate and cloned or altered plan rejects unverified plan first',()=>{const f=duplicateFixture();for(const plan of [{...f.plan},{...f.plan,inputHash:'f'.repeat(64)},{...f.plan,sourceKey:'f'.repeat(64)}])expect(()=>recordSourceEvidenceReading([f.value],plan as any,f.meta)).toThrow('Unverified source evidence plan')});
for(const invalid of ['foreign','repeated','scope'] as const)test('joint duplicate and invalid last observation '+invalid+' checks whole response first',()=>{const f=duplicateFixture();const third=structuredClone(f.one);if(invalid==='foreign')third.evidence.push({sourceRef:'s99999'});else if(invalid==='repeated')third.evidence.push({sourceRef:'s3'});else (third as any).scope='selected_lot';f.value.observations.push(third);let error:any;try{recordSourceEvidenceReading([f.value],f.plan,f.meta)}catch(e){error=e}expect(error).toBeTruthy();expect(error.message).not.toContain('Repeated independent source observation selection')});
function storedDuplicate(){const f=fixture();const r:any=structuredClone(recordSourceEvidenceReading([f.value],f.plan,f.meta));r.responses[0].observations.push(structuredClone(r.responses[0].observations[0]));const rehash=()=>{const {hash,...unsigned}=r;r.hash=createHash('sha256').update(stableDocumentaryJson(unsigned)).digest('hex')};rehash();return{f,r,rehash};}
test('stored duplicate with authentic recomputed record hash rejects duplicate',()=>{const {f,r}=storedDuplicate();expect(()=>readSourceEvidenceReading(r,f.plan)).toThrow(error)});
test('stored duplicate with changed record hash fails integrity first',()=>{const {f,r}=storedDuplicate();r.hash='f'.repeat(64);expect(()=>readSourceEvidenceReading(r,f.plan)).toThrow('Altered independent source evidence')});
for(const field of ['model','sourceKey','inputHash','version','maxTokens'] as const)test('stored duplicate with stale header '+field+' stays null before duplicate',()=>{const {f,r}=storedDuplicate();r[field]=field==='maxTokens'?1024:'f'.repeat(64);expect(readSourceEvidenceReading(r,f.plan)).toBeNull()});
for(const field of ['id','at'] as const)test('stored duplicate with invalid metadata '+field+' fails integrity first',()=>{const {f,r,rehash}=storedDuplicate();r[field]=field==='id'?'':'INVALID_DATE';rehash();expect(()=>readSourceEvidenceReading(r,f.plan)).toThrow('Invalid source evidence metadata')});
test('stored duplicate with cloned plan fails integrity first',()=>{const {f,r}=storedDuplicate();expect(()=>readSourceEvidenceReading(r,{...f.plan} as any)).toThrow('Unverified source evidence plan')});

for(const field of ['scope','reference','quotation'] as const)test('stored duplicate and changed original '+field+' validate ownership before duplicate',()=>{const {f,r,rehash}=storedDuplicate();const observation=r.responses[0].observations[1];if(field==='scope')observation.scope='selected_lot';else if(field==='reference')observation.evidence[1].sourceRef='s99999';else observation.evidence[1].text='FORGED_ORIGINAL_QUOTE';rehash();let error:any;try{readSourceEvidenceReading(r,f.plan)}catch(e){error=e}expect(error).toBeTruthy();expect(error.message).not.toContain('Repeated independent source observation selection')});
